// src/app/chat/components/suggestion-chips/suggestion-chips.component.ts
// Shows grounded follow-up question suggestions below the last assistant message.
// Suggestions are generated by backend using only topics covered in search results.
// Clicking a chip sends it as the next message.

import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
  output,
} from '@angular/core';

@Component({
  selector:        'app-suggestion-chips',
  standalone:      true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (suggestions().length > 0) {
      <div class="chips" role="group" aria-label="Suggested follow-up questions">
        <span class="chips__label">You might also ask:</span>
        <div class="chips__list">
          @for (suggestion of suggestions(); track $index) {
            <button
              class="chips__chip"
              (click)="chipClicked.emit(suggestion)"
              [title]="suggestion"
            >
              {{ suggestion }}
            </button>
          }
        </div>
      </div>
    }
  `,
  styles: [`
    .chips {
      display:        flex;
      flex-direction: column;
      gap:            0.5rem;
      padding:        0.5rem 0;

      &__label {
        font-size:   0.72rem;
        color:       var(--app-text-secondary);
        font-weight: 500;
      }

      &__list {
        display:  flex;
        flex-wrap: wrap;
        gap:      0.4rem;
      }

      &__chip {
        background:    var(--app-bg-container);
        border:        1px solid var(--app-border);
        border-radius: 20px;
        padding:       0.35rem 0.85rem;
        font-size:     0.78rem;
        color:         var(--app-text-primary);
        cursor:        pointer;
        font-family:   inherit;
        transition:    border-color 0.15s ease,
                       background 0.15s ease,
                       color 0.15s ease;
        text-align:    left;
        max-width:     320px;
        white-space:   nowrap;
        overflow:      hidden;
        text-overflow: ellipsis;

        &:hover {
          border-color: #d04a02;
          background:   rgba(208, 74, 2, 0.06);
          color:        #d04a02;
        }

        &:active {
          transform: scale(0.97);
        }
      }
    }
  `],
})
export class SuggestionChipsComponent {
  readonly suggestions  = input<string[]>([]);
  readonly chipClicked  = output<string>();
}